### ISSUE TITLE
Watcher Process Dies

### ISSUE THREAD

**Issue by vmtyler** [vmtyler/vascodagama#2]
Seems to happen when the hashtag is changed. Doesn't happen every time.
```
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    watch_stream()
  File "/Users/tbritten/Dropbox/Documents/Code/vascodagama/log_with/__init__.py", line 47, in wrapper
    f_result = func(*args, **kwds)
  File "/Users/tbritten/Dropbox/Documents/Code/vascodagama/twitter_watch/__init__.py", line 213, in watch_stream
    if not tweet['retweeted'] and 'entities' in tweet and 'media' in tweet['entities'] and \
KeyError: 'retweeted'
```

**Comment by mcowger** [comment]
Just need to check for membership.  Working on it.

**Comment by mcowger** [comment]
To clarify....

the reason this failed sometimes is because I was checking the value of the 'retweeted' key in the 'tweet' dictionary, but sometimes 'tweet' didn't even have a 'retweeted' value to check, so it would bomb out with a 'KeyError'.

By putting in a statement at the beginning checking to make sure it even exists (`'retweeted' in tweet`) before checking its value, I can prevent that.

Now, a better way to do this would be to wrap this in a `try: ... except:...` block, which I should do, because it catches more error types.  Will do that later.
